code

equ	cg_trapPrint							-1
equ	cg_trapError							-2
equ	cg_trapMilliseconds					-3
equ	cg_trapCvar_Register					-4
equ	cg_trapCvar_Update					-5
equ	cg_trapCvar_Set						-6
equ cg_trapCvar_VariableStringBuffer		-7
equ	cg_trapArgc							-8
equ	cg_trapArgv							-9
equ	cg_trapArgs							-10
equ	cg_trapFS_FOpenFile					-11
equ	cg_trapFS_Read						-12
equ	cg_trapFS_Write						-13 
equ	cg_trapFS_FCloseFile					-14
equ	cg_trapSendConsoleCommand				-15
equ	cg_trapAddCommand						-16
equ	cg_trapSendClientCommand				-17
equ	cg_trapUpdateScreen					-18
equ	cg_trapCM_LoadMap						-19
equ	cg_trapCM_NumInlineModels				-20
equ	cg_trapCM_InlineModel					-21
equ	cg_trapCM_LoadModel					-22
equ	cg_trapCM_TempBoxModel				-23
equ	cg_trapCM_PointContents				-24
equ	cg_trapCM_TransformedPointContents	-25
equ	cg_trapCM_BoxTrace					-26
equ	cg_trapCM_TransformedBoxTrace			-27
equ	cg_trapCM_MarkFragments				-28
equ	cg_trapS_StartSound					-29
equ	cg_trapS_StartLocalSound				-30
equ	cg_trapS_ClearLoopingSounds			-31
equ	cg_trapS_AddLoopingSound				-32
equ	cg_trapS_UpdateEntityPosition			-33
equ	cg_trapS_Respatialize					-34
equ	cg_trapS_RegisterSound				-35
equ	cg_trapS_StartBackgroundTrack			-36
equ	cg_trapR_LoadWorldMap					-37
equ	cg_trapR_RegisterModel				-38
equ	cg_trapR_RegisterSkin					-39
equ	cg_trapR_RegisterShader				-40
equ	cg_trapR_ClearScene					-41
equ	cg_trapR_AddRefEntityToScene			-42
equ	cg_trapR_AddPolyToScene				-43
equ	cg_trapR_AddLightToScene				-44
equ	cg_trapR_RenderScene					-45
equ	cg_trapR_SetColor						-46
equ	cg_trapR_DrawStretchPic				-47
equ	cg_trapR_ModelBounds					-48
equ	cg_trapR_LerpTag						-49
equ	cg_trapGetGlconfig					-50
equ	cg_trapGetGameState					-51
equ	cg_trapGetCurrentSnapshotNumber		-52
equ	cg_trapGetSnapshot					-53
equ	cg_trapGetServerCommand				-54
equ	cg_trapGetCurrentCmdNumber			-55
equ	cg_trapGetUserCmd						-56
equ	cg_trapSetUserCmdValue				-57
equ	cg_trapR_RegisterShaderNoMip			-58
equ	cg_trapMemoryRemaining				-59
equ cg_trapR_RegisterFont					-60
equ cg_trapKey_IsDown						-61
equ cg_trapKey_GetCatcher					-62
equ cg_trapKey_SetCatcher					-63
equ cg_trapKey_GetKey						-64
equ cg_trapPC_AddGlobalDefine				-65
equ	cg_trapPC_LoadSource					-66
equ cg_trapPC_FreeSource					-67
equ cg_trapPC_ReadToken					-68
equ cg_trapPC_SourceFileAndLine			-69
equ cg_trapS_StopBackgroundTrack			-70
equ cg_trapRealTime						-71
equ cg_trapSnapVector						-72
equ cg_trapRemoveCommand					-73
equ cg_trapR_LightForPoint				-74
equ cg_trapCIN_PlayCinematic				-75
equ cg_trapCIN_StopCinematic				-76
equ cg_trapCIN_RunCinematic 				-77
equ cg_trapCIN_DrawCinematic				-78
equ cg_trapCIN_SetExtents					-79
equ cg_trapR_RemapShader					-80
equ	cg_trapS_AddRealLoopingSound			-81
equ cg_trapS_StopLoopingSound				-82
equ cg_trapCM_TempCapsuleModel			-83
equ cg_trapCM_CapsuleTrace				-84
equ cg_trapCM_TransformedCapsuleTrace		-85
equ cg_trapR_AddAdditiveLightToScene		-86
equ cg_trapGetEntityToken					-87
equ	cg_trapR_AddPolysToScene				-88
equ cg_trapR_inPVS						-89
equ cg_trapFS_Seek			-90

equ	memset						-101
equ	memcpy						-102
equ	strncpy						-103
equ	sin							-104
equ	cos							-105
equ	atan2						-106
equ	sqrt						-107
equ floor						-108
equ	ceil						-109
equ	testPrintInt				-110
equ	testPrintFloat				-111
equ acos						-112

